name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest tests/

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          # Copy application files to EC2
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r * ec2-user@${EC2_PUBLIC_IP}:/home/ec2-user/app

          # SSH into EC2 and restart the application
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${EC2_PUBLIC_IP} << 'EOF'
            cd /home/ec2-user/app
            pip install -r requirements.txt
            # Restart the Flask app with systemd or gunicorn
            sudo systemctl restart flask-app
          EOF

      - name: Clean up SSH Key
        run: rm ec2_key.pem
