name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Save the SSH private key and set permissions
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          # SSH into EC2 to clone/update the repo and set up the app
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Check if the app directory exists; clone if not
            if [ ! -d "/home/ec2-user/app" ]; then
              git clone https://github.com/sudarshanmehta/llm_be.git /home/ec2-user/app
            else
              cd /home/ec2-user/app
              git pull origin main
            fi
            
            cd /home/ec2-user/app
            # Set up virtual environment and install dependencies
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask-app
          EOF

      - name: Clean up SSH Key
        run: rm ec2_key.pem
