name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # Triggers on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Save the SSH private key and set permissions
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

          # Copy application files to EC2
          scp -o StrictHostKeyChecking=no -i ec2_key.pem -r * ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/app

          # SSH into EC2 and restart the application
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /home/ec2-user/app
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flask-app
          EOF

      - name: Clean up SSH Key
        run: rm ec2_key.pem
